
number = int(input("enter a number"))
temp = number
n = 0
while temp != 0:
    n = (temp % 10) + (n * 10)
    temp = temp // 10
if number == n:
    print("Number is a palindrome")
    print("Number is a palindrome")
    print("Number is a palindrome")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("Number is a palindrome")
    print("Number is a palindrome")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("Number is a palindrome")
    print("Number is a palindrome")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("Number is a palindrome")
    print("Number is a palindrome")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("Number is a palindrome")
    print("Number is a palindrome")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
    print("number is nominal")
else:
    print("number is not a palindrome")

